### PR TITLE
TypeScript@5.0.3 to TypeScript@5.2.2

### PR DESCRIPTION
**Pull request by sidling1**
image

I ran the command `npm install --save-dev typescript@5.2.2` , and then `npm run build`. The build did not give any error's.
Just Check the picture once and then if it's okay merge the PR :)

### CODE REVIEW

**Comment by JamesLMilner** [comment]
Hi @sidling1 thanks for this! This project uses conventional commits so you will need to update your commit message to meet the conventional commit standard.

that could be something like :

`chore: update typescript from version 5.0.3 to 5.2.2`

You can do:

```shell
git commit --amend -m "chore: update typescript from version 5.0.3 to 5.2.2"
```

to change the commit message, then force push it. Once you've done this I can merge it.

**Comment by sidling1** [comment]
@JamesLMilner I did it , Thanks !

**Comment by JamesLMilner** [comment]
Hi @sidling1 sorry about this but it appears this is failing the npm install step of the build pipeline because incompatibility of `typedoc` which this version of typescript. You can do 

```
npm install typedoc@0.25.1
git add package.json 
git add package-lock.json
git commit --amend --no-edit 
```

And then force push. It should resolve the issue. Appreciate your perserverance here and sorry about the added complexity here. Guess this part of the problem of updating dependencies 😓 !

**Comment by sidling1** [comment]
Did it !! @JamesLMilner

**Pull request merged**
