### PR TITLE
Pull Request to Resolve Issue #64 Preventing Polygon Self-Intersection with Select Mode

### PR DESCRIPTION
**Pull request by UncatchableAlex**
The constructor for TerraDrawSelectMode may now contain an additional field called "self_intersectable" that, when toggled true, will allow Polygons or LineStrings to become self-intersecting through edits in select mode. When the self_intersectable field is omitted from teh TerraDrawSelectMode constructor, the default behavior is to prohibit self-intersections from occurring in select mode.

I added an additional parameter in the drag() function of drag-coordinate.behavior.ts to specify whether or not geometry updates containing self-intersections should be saved to the store. If self-intersections are prohibited and the registered mouse event would cause a self-intersection, the attempted geometry changes will not save to the store, and the function will return false. I also wrote new tests and updated existing tests to accomodate this extra parameter.

Thanks for all the guidance you gave me in your comment in my initial issue thread. It helped immensely!

### CODE REVIEW

**Comment by JamesLMilner** [comment]
Hey @UncatchableAlex thanks so much for this - will be an amazing contribution and excited to get it in! 

I tested it and it works great 👍🏻 One small request on the code side - I think we should change the snake case variable `self_intersectable` to camel case `selfIntersectable`.

There is one other issue - I have done something which you probably should not do which is change the git history for the main branch (which is why you see the extra commits from me in your PR). Apologies about this as this is my fault - this is why there are extra commits from me in your PR.

Unfortunately this means that to just get it to register only your commit (hash `c65f6ae9b979d8ec046b96132b735c45d15fd89a`) in the PR we need to remedy this. There are a few ways to do this:

1) As there is only a few changes, create a new folder with git clone of the upstream terra-draw repo and add your changes again manually creating a new commit and PR (probably the simplest?). I would recommend you don't make the changes on `main` branch and instead create a new branch (`select-self-intersectable` for example) to do this.
2) I have a branch where I've git cherry picked your commit onto a branch of the latest `main` branch which you can reraise as a PR. The branch is called `alex-intersect-fix` and this has the correct git history (see https://github.com/JamesLMilner/terra-draw/compare/alex-intersect-fix?expand=1).
3) You can attempt to git cherrypick your commit onto  a clean branch of `main` yourself - which is doable but a bit fiddly.

Again really sorry to cause this fuss - the other option is I can take your cherrypicked commit and make the PR for you, depending on how much energy you want to expend!

**Comment by JamesLMilner** [comment]
If you want to try approach 3) I tried this out myself and it seemed to work:

1) Go on your current folder/branch
2) git remote add upstream git@github.com:JamesLMilner/terra-draw.git
3) git checkout -b old-self-intersect-select
4) git checkout main 
5) git reset --hard upstream/main
6) git checkout -b self-intersect-select
7) git cherry-pick 436793809bcf97d9a4bc761d4071e584c962a194
8) git push origin self-intersect-select
9) Reraise PR from self-intersect-select branch
10) The history should now match 🎉 and your main branch will match current upstream main

you could also make the self_intersectable -> selfIntersectable change at step 8) if you wanted :)

**Comment by UncatchableAlex** [comment]
I followed your suggestions as best as I could, but ended up having problems with the cherry pick. The commit that you suggested cherry-picking from was a merge commit for me, so I cherry-picked one commit further back. I then made the variable name change that you recommended, committed those changes, and did a rebase with a squash to make this branch one commit ahead of your main branch. Here were my steps:

1.) git remote add upstream [git@github.com](mailto:git@github.com):JamesLMilner/terra-draw.git
2.) git checkout -b old-self-intersect-select
3.) git checkout main
4.) git reset --hard upstream/main
5.) git checkout -b self-intersect-select
6.) git cherry-pick fbea6490362c30ace79e0e1aa9337d5b31507c52
7.) change variable name from self_intersectable to selfIntersectable
8.) git commit -m "chore: changed variable name"
9.) git rebase -i HEAD~2 (did a squash on the last name change commit)
10.) git commit --amend (renamed the commit to its current name)
11.) git push --set-upstream origin self-intersect-select
Reraise PR from self-intersect-select branch

Thank you for all of your kind help. This was definitely a learning experience for me. I feel a lot more comfortable with some of these more complex git commands now.

**Comment by JamesLMilner** [comment]
@UncatchableAlex it looks like you are more or less there! There's one small change you'll need to make to the commit message, shouldn't be too hard thankfully :) I've left the instructions on the other PR - I will close this one.

**Pull request closed without merging**
